/**
 * Classification teaser lines for the mascot. Index 0 is the canonical
 * phrasing; later entries are hashed by game node id via `pickQuip`.
 * Authored offline; never generated at runtime.
 */
export const QUIP_BANK = {
  best: [
    "That's the one.",
    "You found it.",
    "Right there.",
    "Spot on.",
    "Clean.",
    "You got it.",
    "Yeah, that.",
    "That'll do it.",
    "Couldn't ask for more.",
    "You saw it.",
    "Just so.",
    "You picked it.",
    "Right on the money.",
    "Hard to top.",
    "You called it.",
    "Nothing better there.",
    "You had it.",
    "Quietly correct.",
    "You read it.",
    "Holds up.",
    "Tracked it.",
    "Does the job.",
    "You landed it.",
    "Well chosen.",
    "Clocked it.",
    "Leaves nothing out.",
    "You sorted it.",
    "Exactly that.",
    "You put it there.",
    "No notes.",
    "Pretty much perfect.",
    "Hit it.",
    "As good as it gets.",
    "Can't argue with that.",
    "Nothing to add.",
    "The right one.",
    "That works.",
    "Just the thing.",
    "Couldn't be cleaner.",
    "Worth keeping.",
    "You got there.",
    "Quietly the best.",
    "Stands up.",
    "Little to improve.",
    "Settled.",
    "Fine work.",
    "Sits well.",
    "Done right.",
    "There it is.",
    "I'd play that too.",
    "Same one I'd take.",
    "Look no further.",
    "We can stop looking.",
    "Play that.",
    "You chose well.",
    "Goes without saying.",
    "You made the call.",
    "You found your move.",
    "You saw what mattered.",
    "Had the read.",
    "You picked a winner.",
    "Got the point.",
    "You found the answer.",
    "Put it well.",
    "Saw the point.",
    "Got the idea.",
    "You found the line.",
    "You played the right one.",
    "You nailed the idea.",
    "You saw it coming.",
    "You found the thread.",
    "You picked the right one.",
    "You put it on the money.",
    "That's it.",
    "On the button.",
    "Couldn't leave that.",
    "Fits.",
    "The one we wanted.",
    "That'll keep.",
    "Right as it gets.",
    "Paid off.",
    "Found the thread.",
    "Called it.",
    "Read it right.",
    "Landed clean.",
    "Took the right path.",
    "Closed it well.",
    "Put it where it belongs.",
    "Sorted.",
    "Keeps everything in place.",
    "All of it, right there.",
    "Couldn't pick better.",
    "Ends the search.",
    "Still the one I'd play.",
    "Nothing I'd change.",
    "That's the idea.",
    "That's the play.",
    "That's your move.",
    "That's the call.",
    "That's the way.",
  ],
  excellent: [
    "Nice.",
    "Well spotted.",
    "Smooth.",
    "You saw that.",
    "Pretty clean.",
    "Well played.",
    "Quietly good.",
    "Neat.",
    "Well seen.",
    "You handled that.",
    "Pretty sharp.",
    "Good eye.",
    "You read that well.",
    "Quietly strong.",
    "Sits nicely.",
    "Well judged.",
    "Crisp.",
    "You found a good one.",
    "Sharp enough.",
    "Tidy work.",
    "A good find.",
    "You caught that.",
    "Cleanly done.",
    "That's a good one.",
    "Well found.",
    "Picked a good one.",
    "Pretty tidy.",
    "Sharp work.",
    "Fine idea.",
    "You saw the trick.",
    "Nicely placed.",
    "That's a keeper.",
    "Quietly clever.",
    "Strong idea.",
    "Good hands.",
    "You kept it clean.",
    "That's well found.",
    "A nice touch.",
    "You read it well.",
    "A fine move.",
    "Held together nicely.",
    "Clever enough.",
    "Polished.",
    "Put that well.",
    "That's a nice find.",
    "Quietly sharp.",
    "Spotted it.",
    "A bright find.",
    "Neatly done.",
    "You chose a good one.",
    "Well picked.",
    "A clean idea.",
    "You made it look easy.",
    "That's a good catch.",
    "Slick.",
    "Had a good read.",
    "That's well placed.",
    "Pretty well found.",
    "You took the good one.",
    "A strong one.",
    "Kept it simple.",
    "You found something good.",
    "Neat work.",
    "You saw a good idea.",
    "A tidy find.",
    "Worked out well.",
    "Played it well.",
    "A smart one.",
    "Fairly sharp.",
    "You kept your head.",
    "Worth holding.",
    "Good sense.",
    "You found a cleaner way.",
    "A nice idea.",
    "Came out well.",
    "Picked well.",
    "A good look.",
    "Quietly on point.",
    "Did it clean.",
    "A neat find.",
    "Held up well.",
    "You found a nice one.",
    "Well timed.",
    "A good one.",
    "Placed that well.",
    "That's a clean find.",
    "Stayed sharp.",
    "You saw it well.",
    "A fine idea.",
    "Came together.",
    "You kept it tidy.",
    "Quietly on the money.",
    "You found a keeper.",
    "A pretty find.",
    "Did that well.",
    "You made a good call.",
    "Good, quietly.",
    "You found a sweet spot.",
    "That's a clean idea.",
    "Well handled.",
  ],
  good: [
    "Solid.",
    "Fine.",
    "Playable.",
    "Holds.",
    "Fair.",
    "Reasonable.",
    "Decent.",
    "That'll do.",
    "Not bad.",
    "Fine by me.",
    "Nothing flashy.",
    "Fair enough.",
    "Gets the job done.",
    "Keeps you in it.",
    "You can live with that.",
    "No harm done.",
    "Works well enough.",
    "Keeps things steady.",
    "That's okay.",
    "That's fine.",
    "That's alright.",
    "Playable enough.",
    "Steady enough.",
    "Sound enough.",
    "Enough for now.",
    "Workable.",
    "A fair move.",
    "A fair call.",
    "A decent one.",
    "Sensible.",
    "Practical.",
    "Calm.",
    "Safe.",
    "Even keel.",
    "Good enough.",
    "Keeps pace.",
    "Stays with it.",
    "Still fine.",
    "Fine for now.",
    "Holds for now.",
    "Holds up okay.",
    "Stays on track.",
    "Stays playable.",
    "Holds its own.",
    "Holds together.",
    "Keeps the game going.",
    "Keeps you going.",
    "Keeps the door open.",
    "Keeps the balance.",
    "Keeps it simple.",
    "You stayed with it.",
    "You kept it going.",
    "You stayed solid.",
    "You stayed in the game.",
    "You kept it reasonable.",
    "You played it safe.",
    "You didn't overreach.",
    "You can live there.",
    "Doesn't give much away.",
    "Nothing to dislike.",
    "Nothing wrong there.",
    "Still okay.",
    "Still in good shape.",
    "Still with the game.",
    "Ordinary, in a good way.",
    "Fine and simple.",
    "Fair play.",
    "Does the basic job.",
    "A quiet one.",
    "Modest.",
    "A no-fuss move.",
    "A bread-and-butter one.",
    "Sit tight.",
    "Works.",
    "Regular.",
    "Gentle.",
    "A quiet hold.",
    "A fair keep.",
    "Holding steady.",
    "Keep going.",
    "That's alright by me.",
    "In the mix.",
    "Standard.",
    "Everyday move.",
    "That's a quiet one.",
    "Tidy enough.",
    "A quiet keep.",
    "Does no harm.",
    "Keeps your feet under you.",
    "Quietly fine.",
    "Holds the fort.",
    "I'll take it.",
    "Keeps you level.",
    "Held your ground.",
    "A keep-going move.",
    "Stays even.",
    "A no-drama move.",
    "You kept it calm.",
    "Plenty for now.",
    "Living with that.",
  ],
  inaccuracy: [
    "There's better.",
    "A little loose.",
    "You can do better.",
    "Almost.",
    "Close, but there's more.",
    "Worth a second look.",
    "Not quite.",
    "A bit off.",
    "There's a cleaner way.",
    "Slightly off.",
    "There's another idea.",
    "A tad loose.",
    "Missed a better one.",
    "Try the nicer path.",
    "Just a bit wide.",
    "Go tighter.",
    "Not the cleanest.",
    "A little soft.",
    "You left something.",
    "There's more there.",
    "Nearly.",
    "A shade off.",
    "There's a better idea.",
    "Could be cleaner.",
    "Wide of it.",
    "Not quite the one.",
    "Look for the sharper idea.",
    "Just shy.",
    "There was a neater one.",
    "A bit fuzzy.",
    "You can tighten that.",
    "There's a better place for that.",
    "Slightly beside the point.",
    "A better one was sitting there.",
    "Not your best.",
    "A stronger one sat there.",
    "Drifted sideways.",
    "You came close.",
    "Could've gone cleaner.",
    "Just a hair off.",
    "Worth another think.",
    "Take the shorter path.",
    "Not quite it.",
    "You skipped a better one.",
    "The calmer idea was there.",
    "Slightly roundabout.",
    "A better move was nearby.",
    "Not the tidiest.",
    "Quieter would've been better.",
    "A touch off.",
    "You can find better.",
    "Try a different take.",
    "Close, not quite.",
    "Simpler would do it.",
    "Just missed a better one.",
    "A bit of a detour.",
    "Try a different spot.",
    "Not exactly.",
    "Not quite ideal.",
    "You had a better one.",
    "Not the best fit.",
    "Took the long way.",
    "A better idea was waiting.",
    "Not the strongest.",
    "Missed a better read.",
    "Could use a second look.",
    "The cleaner take was there.",
    "You were close.",
    "Look from another angle.",
    "A little off the mark.",
    "Not quite what we wanted.",
    "Just a little wide.",
    "A better one was there.",
    "There's room for a better one.",
    "There's a better way.",
    "Could've been tidier.",
    "Could hold firmer.",
    "Not the idea I'd take.",
    "Another choice was better.",
    "Close, but look again.",
    "Off to the side.",
    "Finish it cleaner.",
    "You left a better one.",
    "Another pick was better.",
    "Look once more?",
    "More was available.",
    "Take a cleaner step.",
    "Not quite the cleanest.",
    "Want a cleaner one?",
    "A better one was right there.",
    "Second thought?",
    "You can still find better.",
    "A better idea nearby.",
    "A bit away from the best.",
    "A nicer idea sat there.",
    "Could be tighter.",
    "Take the cleaner route.",
    "Not the one I'd keep.",
    "Let's find the cleaner one.",
    "A bit of extra walking.",
  ],
  mistake: [
    "That was shaky.",
    "That one slipped.",
    "That gave something.",
    "That wobbled.",
    "That cost you.",
    "That one leaked.",
    "That left a hole.",
    "That got loose.",
    "That helped them.",
    "That didn't land.",
    "That opened a door.",
    "That was a slip.",
    "That left you open.",
    "That didn't help.",
    "That asked for trouble.",
    "That wasn't the one.",
    "Let's look again.",
    "Let's rewind a bit.",
    "Let's sit with that.",
    "Let's check that.",
    "Let's look twice.",
    "Let's pause on that.",
    "Let's see that again.",
    "Let's take another look.",
    "Let's try a different idea.",
    "Let's look before we keep it.",
    "Let's not keep that.",
    "Let's rewind.",
    "Let's find a sturdier one.",
    "Let's check the idea.",
    "Let's look at the other idea.",
    "Let's not skip past that.",
    "Let's look back.",
    "Let's see if we keep that.",
    "Let's treat that as a miss.",
    "Let's look at that one.",
    "Let's slow down here.",
    "Let's hold on that.",
    "Let's give that another pass.",
    "Let's not rush this one.",
    "Let's back up a little.",
    "Let's see the other option.",
    "Let's look at the leak.",
    "Let's try the other door.",
    "Let's sit on this one.",
    "Let's check twice.",
    "Let's find a safer idea.",
    "Let's not skip the wobble.",
    "Want to rewind?",
    "Want to try that over?",
    "Want another pass?",
    "Want to think once more?",
    "Want to walk that back?",
    "Want to look twice?",
    "Want to undo that?",
    "Want to sit with that?",
    "Want to try again?",
    "Want to take a beat?",
    "Want to go back a step?",
    "Want to peek at that again?",
    "Want to check the other idea?",
    "Want to keep that?",
    "Want to rethink it?",
    "Want a second pass?",
    "Might want a redo.",
    "Might want that back.",
    "Might be a miss.",
    "Might rethink that.",
    "Might want a second pass.",
    "Might be the wrong door.",
    "Might've given too much.",
    "Might want a sturdier idea.",
    "Hmm, maybe not.",
    "A bit shaky, yeah.",
    "A little dangerous.",
    "Maybe not that.",
    "Kind of shaky.",
    "A bit much.",
    "Soft, that one.",
    "A shaky step.",
    "Kind of a miss.",
    "A little too hopeful.",
    "A miss, I think.",
    "A bit of a stumble.",
    "A little too far.",
    "Kind of a leak.",
    "Worth taking back?",
    "Worth a rewind?",
    "Second look?",
    "Maybe take that back.",
    "A bit of a leak.",
    "A wobbly one.",
    "Kind of thin.",
    "A little leaky.",
    "A slip, maybe.",
    "Kind of a wobble.",
    "A bit of trouble there.",
    "Maybe a miss.",
    "A shaky one to keep.",
    "Hoping a bit much.",
  ],
  blunder: [
    "Want to look at that?",
    "Want a do-over?",
    "Want that one back?",
    "Want to rewind that?",
    "Want to see the other idea?",
    "Want to walk it back?",
    "Want to look once more?",
    "Want to see why that hurts?",
    "Want to pause on that?",
    "Want to look at the cost?",
    "Want to try a different one?",
    "Want to see the other path?",
    "Want to go back?",
    "Want to see it again?",
    "Want to sit with this?",
    "Want to look before we go on?",
    "Want to look twice?",
    "Want to back up?",
    "Want to take that back?",
    "Want to sit with the miss?",
    "Let's rewind.",
    "Let's take that back.",
    "Let's look at that again.",
    "Let's sit with this one.",
    "Let's find what happened.",
    "Let's look twice at that.",
    "Let's not keep that.",
    "Let's take another pass.",
    "Let's rewind and look.",
    "Let's check what that did.",
    "Let's look before we move on.",
    "Let's go back a move.",
    "Let's find the safer idea.",
    "Let's treat that as a miss.",
    "Let's see the better idea.",
    "Let's not skip this one.",
    "Let's look at what that lost.",
    "Let's rewind this.",
    "Let's catch that.",
    "Let's take a beat on that.",
    "Let's look at the damage.",
    "Let's find what slipped.",
    "Let's look at that miss.",
    "Let's look together.",
    "Let's back up a step.",
    "That one hurt.",
    "That gave too much.",
    "That one got away from you.",
    "That was a big slip.",
    "That opened the door too wide.",
    "That cost a lot.",
    "That one really leaked.",
    "That was a drop.",
    "That was a hole.",
    "That gave away too much.",
    "That one stung.",
    "That left the door open.",
    "That put you in trouble.",
    "That was a heavy miss.",
    "That one got expensive.",
    "That was the one to catch.",
    "That dropped something big.",
    "That was a lot to give.",
    "Might want that back.",
    "You may want that one back.",
    "You might not want that.",
    "You may want a second look.",
    "You might want a rewind.",
    "You may want to look twice.",
    "Might want a closer look.",
    "You might want this one back.",
    "Worth another look?",
    "Worth sitting with that one.",
    "Did that feel right?",
    "A big slip.",
    "Yeah, a hole there.",
    "Big drop.",
    "A heavy miss.",
    "A wide miss.",
    "A big swing.",
    "A big wobble.",
    "A miss to sit with.",
    "A hard one to keep.",
    "Dropped off.",
    "A lot to give.",
    "A miss worth seeing.",
    "Leaked badly.",
    "Really gave them a look.",
    "Opened a path for them.",
    "Put a dent in it.",
    "Left you in a hole.",
    "Handed them too much.",
    "Gave them too much air.",
    "Left a big hole.",
    "Cost more than it looked.",
    "The expensive one.",
    "The one to catch early.",
    "We should sit with this.",
    "Asked for a rewind.",
    "Got away from us.",
  ],
} as const;

export type QuipBankKey = keyof typeof QUIP_BANK;

function hashSeed(text: string): number {
  let h = 2166136261;
  for (let i = 0; i < text.length; i += 1) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

export function pickQuip(
  classification: QuipBankKey,
  seed: string | undefined,
): string {
  const variants = QUIP_BANK[classification];
  const first = variants[0];
  if (!seed) return first;
  const index = hashSeed(`${seed}:${classification}`) % variants.length;
  return variants[index] ?? first;
}
